USE GD1C2014;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_FUNCIONALIDAD_X_ROL_FUNCIONALIDAD') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE FUNCIONALIDAD_X_ROL DROP CONSTRAINT FK_FUNCIONALIDAD_X_ROL_FUNCIONALIDAD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_FUNCIONALIDAD_X_ROL_ROL') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE FUNCIONALIDAD_X_ROL DROP CONSTRAINT FK_FUNCIONALIDAD_X_ROL_ROL;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_USUARIO_CLIENTE') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_CLIENTE;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_USUARIO_EMPRESA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_EMPRESA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_USUARIO_LOCALIDAD') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_LOCALIDAD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PUBLICACION_ESTADO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PUBLICACION DROP CONSTRAINT FK_PUBLICACION_ESTADO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PUBLICACION_TIPO_PUBLICACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PUBLICACION DROP CONSTRAINT FK_PUBLICACION_TIPO_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PUBLICACION_USUARIO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PUBLICACION DROP CONSTRAINT FK_PUBLICACION_USUARIO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PUBLICACION_VISIBILIDAD_PUBLICACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PUBLICACION DROP CONSTRAINT FK_PUBLICACION_VISIBILIDAD_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_RUBROS_X_PUBLICACION_PUBLICACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE RUBROS_X_PUBLICACION DROP CONSTRAINT FK_RUBROS_X_PUBLICACION_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_RUBROS_X_PUBLICACION_RUBRO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE RUBROS_X_PUBLICACION DROP CONSTRAINT FK_RUBROS_X_PUBLICACION_RUBRO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CALIFICACION_PUBLICACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CALIFICACION DROP CONSTRAINT FK_CALIFICACION_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_CALIFICACION_USUARIO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE CALIFICACION DROP CONSTRAINT FK_CALIFICACION_USUARIO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_COMPRA_PUBLICACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE COMPRA DROP CONSTRAINT FK_COMPRA_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_COMPRA_USUARIO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE COMPRA DROP CONSTRAINT FK_COMPRA_USUARIO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_FACTURA_FORMA_PAGO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE FACTURA DROP CONSTRAINT FK_FACTURA_FORMA_PAGO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_FACTURA_USUARIO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE FACTURA DROP CONSTRAINT FK_FACTURA_USUARIO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_FACTURA_ITEM_FACTURA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE FACTURA_ITEM DROP CONSTRAINT FK_FACTURA_ITEM_FACTURA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_FACTURA_ITEM_PUBLICACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE FACTURA_ITEM DROP CONSTRAINT FK_FACTURA_ITEM_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_OFERTA_PUBLICACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE OFERTA DROP CONSTRAINT FK_OFERTA_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_OFERTA_USUARIO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE OFERTA DROP CONSTRAINT FK_OFERTA_USUARIO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PREGUNTA_PUBLICACION') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PREGUNTA DROP CONSTRAINT FK_PREGUNTA_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_PREGUNTA_USUARIO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE PREGUNTA DROP CONSTRAINT FK_PREGUNTA_USUARIO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_ROLES_X_USUARIO_ROL') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE ROLES_X_USUARIO DROP CONSTRAINT FK_ROLES_X_USUARIO_ROL;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_ROLES_X_USUARIO_USUARIO') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE ROLES_X_USUARIO DROP CONSTRAINT FK_ROLES_X_USUARIO_USUARIO;



IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CLIENTE') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CLIENTE;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('EMPRESA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE EMPRESA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FUNCIONALIDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE FUNCIONALIDAD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FUNCIONALIDAD_X_ROL') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE FUNCIONALIDAD_X_ROL;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ROL') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ROL;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('USUARIO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE USUARIO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('LOCALIDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE LOCALIDAD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ESTADO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ESTADO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PUBLICACION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('RUBRO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE RUBRO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('RUBROS_X_PUBLICACION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE RUBROS_X_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('TIPO_PUBLICACION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE TIPO_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('VISIBILIDAD_PUBLICACION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE VISIBILIDAD_PUBLICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CALIFICACION') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CALIFICACION;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('COMPRA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE COMPRA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FACTURA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE FACTURA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FACTURA_ITEM') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE FACTURA_ITEM;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FORMA_PAGO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE FORMA_PAGO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('OFERTA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE OFERTA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('PREGUNTA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE PREGUNTA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ROLES_X_USUARIO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ROLES_X_USUARIO;


CREATE TABLE CLIENTE ( 
	ID bigint identity(1,1)  NOT NULL,
	NOMBRE nvarchar(max) NOT NULL,
	APELLIDO nvarchar(max) NOT NULL,
	DNI numeric(18) NOT NULL,
	DNI_TIPO char(3) NOT NULL,
	FECHA_NAC datetime NOT NULL
);

CREATE TABLE EMPRESA ( 
	CUIT bigint NOT NULL,
	RAZON_SOCIAL nvarchar(max) NOT NULL,
	CONTACTO nvarchar(max) NOT NULL,
	FECHA_CREACION datetime NOT NULL
);

CREATE TABLE FUNCIONALIDAD ( 
	ID int identity(1,1)  NOT NULL,
	NOMBRE nvarchar(max) NOT NULL
);

CREATE TABLE FUNCIONALIDAD_X_ROL ( 
	ROL_ID int NOT NULL,
	FUNCIONALIDAD_ID int NOT NULL
);

CREATE TABLE ROL ( 
	ID int identity(1,1)  NOT NULL,
	NOMBRE nvarchar(50) NOT NULL,
	HABILITADO bit DEFAULT 1 NOT NULL,
	ELIMINADO bit DEFAULT 0 NOT NULL
);

CREATE TABLE USUARIO ( 
	ID bigint identity(1,1)  NOT NULL,
	USERNAME nvarchar(50) NOT NULL,
	PASSWORD nvarchar(max) NOT NULL,
	CLIENTE_ID bigint,
	EMPRESA_ID bigint,
	LOGIN_FALLIDOS int DEFAULT 0 NOT NULL,
	HABILITADO bit DEFAULT 1 NOT NULL,
	ELIMINADO bit DEFAULT 0 NOT NULL,
	MAIL nvarchar(50) NOT NULL,
	TELEFONO int NOT NULL,
	COD_POSTAL int NOT NULL,
	DIRECCION nvarchar(max) NOT NULL,
	PISO numeric(18) NOT NULL,
	DTO nvarchar(50) NOT NULL
);

CREATE TABLE LOCALIDAD ( 
	COD_POSTAL int NOT NULL,
	NOMBRE nvarchar(max) NOT NULL
);

CREATE TABLE ESTADO ( 
	ID smallint identity(1,1)  NOT NULL,
	DESCRIPCION nvarchar(max) NOT NULL
);

CREATE TABLE PUBLICACION ( 
	ID numeric(18) identity(1,1)  NOT NULL,
	USUARIO_ID bigint NOT NULL,
	DESCRIPCION nvarchar(max) NOT NULL,
	UNIDADES numeric(18) NOT NULL,
	PRECIO numeric(18,2) NOT NULL,
	FEC_INICIO datetime NOT NULL,
	FEC_FIN datetime NOT NULL,
	TIPO_PUBLICACION_ID smallint NOT NULL,
	ESTADO_ID smallint NOT NULL,
	VISIBILIDAD_ID smallint NOT NULL,
	ADMITE_PREGUNTAS bit DEFAULT 1 NOT NULL
);

CREATE TABLE RUBRO ( 
	CODIGO int identity(1,1)  NOT NULL,
	DESCRIPCION varchar(max) NOT NULL
);

CREATE TABLE RUBROS_X_PUBLICACION ( 
	PUBLICACION_ID numeric(18) NOT NULL,
	RUBRO_ID int NOT NULL
);

CREATE TABLE TIPO_PUBLICACION ( 
	ID smallint identity(1,1)  NOT NULL,
	DESCRIPCION nvarchar(max) NOT NULL
);

CREATE TABLE VISIBILIDAD_PUBLICACION ( 
	ID smallint NOT NULL,
	DESCRIPCION nvarchar(max) NOT NULL,
	PRECIO int NOT NULL,
	PORC_GANANCIA float NOT NULL
);

CREATE TABLE CALIFICACION ( 
	ID numeric(18) identity(1,1)  NOT NULL,
	USUARIO_ID bigint NOT NULL,
	PUBLICACION_ID numeric(18) NOT NULL,
	PUNTAJE numeric(18) NOT NULL,
	DETALLE nvarchar(max)
);

CREATE TABLE COMPRA ( 
	ID bigint identity(1,1)  NOT NULL,
	USUARIO_ID bigint NOT NULL,
	PUBLICACION_ID numeric(18) NOT NULL,
	CANTIDAD numeric(18) NOT NULL,
	FECHA datetime NOT NULL
);

CREATE TABLE FACTURA ( 
	ID numeric(18) identity(1,1)  NOT NULL,
	USUARIO_ID bigint NOT NULL,
	FECHA datetime NOT NULL,
	FORMA_PAGO_ID smallint NOT NULL,
	CODIGO_TARJETA bigint
);

CREATE TABLE FACTURA_ITEM ( 
	ID bigint identity(1,1)  NOT NULL,
	FACTURA_ID numeric(18) NOT NULL,
	PUBLICACION_ID numeric(18) NOT NULL,
	CANTIDAD numeric(18) NOT NULL,
	MONTO numeric(18,2) NOT NULL,
	DETALLE nvarchar(max) NOT NULL
);

CREATE TABLE FORMA_PAGO ( 
	ID smallint identity(1,1)  NOT NULL,
	DESCRIPCION nvarchar(max) NOT NULL
);

CREATE TABLE OFERTA ( 
	ID bigint identity(1,1)  NOT NULL,
	USUARIO_ID bigint NOT NULL,
	PUBLICACION_ID numeric(18) NOT NULL,
	FECHA datetime NOT NULL,
	MONTO numeric(18) NOT NULL,
	COMPRO bit DEFAULT 0 NOT NULL
);

CREATE TABLE PREGUNTA ( 
	ID bigint identity(1,1)  NOT NULL,
	USUARIO_ID bigint NOT NULL,
	PUBLICACION_ID numeric(18) NOT NULL,
	PREGUNTA nvarchar(max) NOT NULL,
	FEC_PREG datetime NOT NULL,
	RESPUESTA nvarchar(max),
	FEC_RESP datetime
);

CREATE TABLE ROLES_X_USUARIO ( 
	USUARIO_ID bigint NOT NULL,
	ROL_ID int NOT NULL
);


ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA 
	PRIMARY KEY CLUSTERED (CUIT);

ALTER TABLE FUNCIONALIDAD ADD CONSTRAINT PK_FUNCIONALIDAD 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE FUNCIONALIDAD_X_ROL ADD CONSTRAINT PK_FUNCIONALIDAD_X_ROL 
	PRIMARY KEY CLUSTERED (ROL_ID, FUNCIONALIDAD_ID);

ALTER TABLE ROL ADD CONSTRAINT PK_ROL 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE LOCALIDAD ADD CONSTRAINT PK_LOCALIDAD 
	PRIMARY KEY CLUSTERED (COD_POSTAL);

ALTER TABLE ESTADO ADD CONSTRAINT PK_ESTADO 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE PUBLICACION ADD CONSTRAINT PK_PUBLICACION 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE RUBRO ADD CONSTRAINT PK_RUBRO 
	PRIMARY KEY CLUSTERED (CODIGO);

ALTER TABLE RUBROS_X_PUBLICACION ADD CONSTRAINT PK_RUBROS_X_PUBLICACION 
	PRIMARY KEY CLUSTERED (PUBLICACION_ID, RUBRO_ID);

ALTER TABLE TIPO_PUBLICACION ADD CONSTRAINT PK_TIPO_PUBLICACION 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE VISIBILIDAD_PUBLICACION ADD CONSTRAINT PK_VISIBILIDAD_PUBLICACION 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE CALIFICACION ADD CONSTRAINT PK_CALIFICACION 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE COMPRA ADD CONSTRAINT PK_COMPRA 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE FACTURA ADD CONSTRAINT PK_FACTURA 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE FACTURA_ITEM ADD CONSTRAINT PK_FACTURA_ITEM 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE FORMA_PAGO ADD CONSTRAINT PK_FORMA_PAGO 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE OFERTA ADD CONSTRAINT PK_OFERTA 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE PREGUNTA ADD CONSTRAINT PK_PREGUNTA 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE ROLES_X_USUARIO ADD CONSTRAINT PK_ROLES_X_USUARIO 
	PRIMARY KEY CLUSTERED (USUARIO_ID, ROL_ID);



ALTER TABLE FUNCIONALIDAD_X_ROL ADD CONSTRAINT FK_FUNCIONALIDAD_X_ROL_FUNCIONALIDAD 
	FOREIGN KEY (FUNCIONALIDAD_ID) REFERENCES FUNCIONALIDAD (ID);

ALTER TABLE FUNCIONALIDAD_X_ROL ADD CONSTRAINT FK_FUNCIONALIDAD_X_ROL_ROL 
	FOREIGN KEY (ROL_ID) REFERENCES ROL (ID);

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_CLIENTE 
	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID);

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_EMPRESA 
	FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (CUIT);

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_LOCALIDAD 
	FOREIGN KEY (COD_POSTAL) REFERENCES LOCALIDAD (COD_POSTAL);

ALTER TABLE PUBLICACION ADD CONSTRAINT FK_PUBLICACION_ESTADO 
	FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID);

ALTER TABLE PUBLICACION ADD CONSTRAINT FK_PUBLICACION_TIPO_PUBLICACION 
	FOREIGN KEY (TIPO_PUBLICACION_ID) REFERENCES TIPO_PUBLICACION (ID);

ALTER TABLE PUBLICACION ADD CONSTRAINT FK_PUBLICACION_USUARIO 
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);

ALTER TABLE PUBLICACION ADD CONSTRAINT FK_PUBLICACION_VISIBILIDAD_PUBLICACION 
	FOREIGN KEY (VISIBILIDAD_ID) REFERENCES VISIBILIDAD_PUBLICACION (ID);

ALTER TABLE RUBROS_X_PUBLICACION ADD CONSTRAINT FK_RUBROS_X_PUBLICACION_PUBLICACION 
	FOREIGN KEY (PUBLICACION_ID) REFERENCES PUBLICACION (ID);

ALTER TABLE RUBROS_X_PUBLICACION ADD CONSTRAINT FK_RUBROS_X_PUBLICACION_RUBRO 
	FOREIGN KEY (RUBRO_ID) REFERENCES RUBRO (CODIGO);

ALTER TABLE CALIFICACION ADD CONSTRAINT FK_CALIFICACION_PUBLICACION 
	FOREIGN KEY (PUBLICACION_ID) REFERENCES PUBLICACION (ID);

ALTER TABLE CALIFICACION ADD CONSTRAINT FK_CALIFICACION_USUARIO 
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);

ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_PUBLICACION 
	FOREIGN KEY (PUBLICACION_ID) REFERENCES PUBLICACION (ID);

ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_USUARIO 
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);

ALTER TABLE FACTURA ADD CONSTRAINT FK_FACTURA_FORMA_PAGO 
	FOREIGN KEY (FORMA_PAGO_ID) REFERENCES FORMA_PAGO (ID);

ALTER TABLE FACTURA ADD CONSTRAINT FK_FACTURA_USUARIO 
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);

ALTER TABLE FACTURA_ITEM ADD CONSTRAINT FK_FACTURA_ITEM_FACTURA 
	FOREIGN KEY (FACTURA_ID) REFERENCES FACTURA (ID);

ALTER TABLE FACTURA_ITEM ADD CONSTRAINT FK_FACTURA_ITEM_PUBLICACION 
	FOREIGN KEY (PUBLICACION_ID) REFERENCES PUBLICACION (ID);

ALTER TABLE OFERTA ADD CONSTRAINT FK_OFERTA_PUBLICACION 
	FOREIGN KEY (PUBLICACION_ID) REFERENCES PUBLICACION (ID);

ALTER TABLE OFERTA ADD CONSTRAINT FK_OFERTA_USUARIO 
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);

ALTER TABLE PREGUNTA ADD CONSTRAINT FK_PREGUNTA_PUBLICACION 
	FOREIGN KEY (PUBLICACION_ID) REFERENCES PUBLICACION (ID);

ALTER TABLE PREGUNTA ADD CONSTRAINT FK_PREGUNTA_USUARIO 
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);

ALTER TABLE ROLES_X_USUARIO ADD CONSTRAINT FK_ROLES_X_USUARIO_ROL 
	FOREIGN KEY (ROL_ID) REFERENCES ROL (ID);

ALTER TABLE ROLES_X_USUARIO ADD CONSTRAINT FK_ROLES_X_USUARIO_USUARIO 
	FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);
