USE GD1C2014;
GO

--	Inserts para tabla maestra ROL

           
INSERT INTO [GD1C2014].[GOODTIMES].[ROL]
           ([NOMBRE])
     VALUES
           ('Empresa')
GO
           
INSERT INTO [GD1C2014].[GOODTIMES].[ROL]
           ([NOMBRE])
     VALUES
           ('Cliente')

INSERT INTO [GD1C2014].[GOODTIMES].[ROL]
           ([NOMBRE])
     VALUES
           ('Administrativo')

--	Inserts para tabla maestra ESTADO
INSERT INTO [GD1C2014].[GOODTIMES].[ESTADO]
           ([DESCRIPCION])
     VALUES
           ('Borrador')
INSERT INTO [GD1C2014].[GOODTIMES].[ESTADO]
           ([DESCRIPCION])
     VALUES
           ('Activa')
INSERT INTO [GD1C2014].[GOODTIMES].[ESTADO]
           ([DESCRIPCION])
     VALUES
           ('Pausada')
INSERT INTO [GD1C2014].[GOODTIMES].[ESTADO]
           ([DESCRIPCION])
     VALUES
           ('Finalizada')
GO

--	Inserts para tabla maestra TIPO_PUBLICACION
INSERT INTO [GD1C2014].[GOODTIMES].[TIPO_PUBLICACION]
           ([DESCRIPCION])
     VALUES
           ('Compra inmediata')
INSERT INTO [GD1C2014].[GOODTIMES].[TIPO_PUBLICACION]
           ([DESCRIPCION])
     VALUES
           ('Subasta')
GO


--	Inserts para tabla maestra RUBRO
INSERT INTO [GD1C2014].[GOODTIMES].[RUBRO]
           ([DESCRIPCION])
     VALUES
           ('Entretenimiento')
INSERT INTO [GD1C2014].[GOODTIMES].[RUBRO]
           ([DESCRIPCION])
     VALUES
           ('Hogar')
INSERT INTO [GD1C2014].[GOODTIMES].[RUBRO]
           ([DESCRIPCION])
     VALUES
           ('Cuidado personal')
GO

-- Insert de administrador, password: admin

INSERT INTO GOODTIMES.USUARIO (USERNAME, PASSWORD, LOGIN_FALLIDOS, HABILITADO, ELIMINADO, MAIL, TELEFONO, DIRECCION, CODIGO_POSTAL, LOCALIDAD, ROL_ID)
VALUES ('admin', 'e6b87050bfcb8143fcb8db0170a4dc9ed00d904ddd3e2a4ad1b1e8dc0fdc9be7', 0, 1, 0, 'admin@admin.com', '1122334455', '', '', 'Buenos Aires', 3);

-- Inserts para las funcionalidades

DECLARE @func_facturar int
insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('FACTURAR_PUBLICACIONES');
SET @func_facturar = SCOPE_IDENTITY()

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, @func_facturar);

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, @func_facturar);

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, @func_facturar);

DECLARE @func_generar int
insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('GENERAR_PUBLICACION');
set @func_generar = SCOPE_IDENTITY()

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, @func_generar);
insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, @func_generar);
insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, @func_generar);

DECLARE @func_MIS_PUBLICACIONES int
insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('MIS_PUBLICACIONES');
set @func_MIS_PUBLICACIONES = SCOPE_IDENTITY()

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, @func_MIS_PUBLICACIONES);
insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, @func_MIS_PUBLICACIONES);
insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, @func_MIS_PUBLICACIONES);

DECLARE @func_historial int
insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('HISTORIAL');
SET @func_historial = SCOPE_IDENTITY()

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, @func_historial);

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, @func_historial);

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, @func_historial);

DECLARE @func_calificar int
insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('CALIFICAR');
SET @func_calificar = SCOPE_IDENTITY()

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, @func_calificar);

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, @func_calificar);

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, @func_calificar);

DECLARE @func_COMPRAR_OFERTAR int
insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('COMPRAR_OFERTAR');
SET @func_COMPRAR_OFERTAR = SCOPE_IDENTITY()

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, @func_COMPRAR_OFERTAR);
insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, @func_COMPRAR_OFERTAR);

DECLARE @func_PREGUNTAS_REALIZADAS int
insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('PREGUNTAS_REALIZADAS');
SET @func_PREGUNTAS_REALIZADAS = SCOPE_IDENTITY()

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, @func_PREGUNTAS_REALIZADAS);
insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, @func_PREGUNTAS_REALIZADAS);

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('ABM_CLIENTE');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('ABM_EMPRESA');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('ABM_VISIBILIDAD');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('ABM_ROL');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('LISTADO_ESTADISTICO');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

-- Forma de pago (la agrego por no estar en la migracion en ningun pago)
INSERT INTO [GOODTIMES].[FORMA_PAGO] ([DESCRIPCION]) VALUES ('Tarjeta de credito')


GO