USE GD1C2014;
GO

--	Inserts para tabla maestra ROL

           
INSERT INTO [GD1C2014].[GOODTIMES].[ROL]
           ([NOMBRE])
     VALUES
           ('Empresa')
GO

INSERT INTO [GD1C2014].[GOODTIMES].[ROL]
           ([NOMBRE])
     VALUES
           ('Administrativo')
           
INSERT INTO [GD1C2014].[GOODTIMES].[ROL]
           ([NOMBRE])
     VALUES
           ('Cliente')


--	Inserts para tabla maestra ESTADO
INSERT INTO [GD1C2014].[GOODTIMES].[ESTADO]
           ([DESCRIPCION])
     VALUES
           ('Borrador')
INSERT INTO [GD1C2014].[GOODTIMES].[ESTADO]
           ([DESCRIPCION])
     VALUES
           ('Activa')
INSERT INTO [GD1C2014].[GOODTIMES].[ESTADO]
           ([DESCRIPCION])
     VALUES
           ('Pausada')
INSERT INTO [GD1C2014].[GOODTIMES].[ESTADO]
           ([DESCRIPCION])
     VALUES
           ('Finalizada')
GO

--	Inserts para tabla maestra TIPO_PUBLICACION
INSERT INTO [GD1C2014].[GOODTIMES].[TIPO_PUBLICACION]
           ([DESCRIPCION])
     VALUES
           ('Compra inmediata')
INSERT INTO [GD1C2014].[GOODTIMES].[TIPO_PUBLICACION]
           ([DESCRIPCION])
     VALUES
           ('Subasta')
GO


--	Inserts para tabla maestra RUBRO
INSERT INTO [GD1C2014].[GOODTIMES].[RUBRO]
           ([DESCRIPCION])
     VALUES
           ('Entretenimiento')
INSERT INTO [GD1C2014].[GOODTIMES].[RUBRO]
           ([DESCRIPCION])
     VALUES
           ('Hogar')
INSERT INTO [GD1C2014].[GOODTIMES].[RUBRO]
           ([DESCRIPCION])
     VALUES
           ('Cuidado personal')
GO

-- Insert de administrador, password: admin

INSERT INTO GOODTIMES.USUARIO (USERNAME, PASSWORD, LOGIN_FALLIDOS, HABILITADO, ELIMINADO, MAIL, TELEFONO, DIRECCION, CODIGO_POSTAL, LOCALIDAD)
VALUES ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 0, 1, 0, 'admin@admin.com', '1122334455', '', '', 'Buenos Aires');

	INSERT INTO GOODTIMES.ROLES_X_USUARIO VALUES (SCOPE_IDENTITY(), 1);

-- Inserts para las funcionalidades
insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('GENERAR_PUBLICACION');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('MIS_PUBLICACIONES');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('HISTORIAL');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('CALIFICAR');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (1, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('CALIFICAR');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('COMPRAR_OFERTAR');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('PREGUNTAS_REALIZADAS');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('HISTORIAL');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (2, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('ABM_CLIENTE');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('ABM_EMPRESA');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('ABM_VISIBILIDAD');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

insert into GOODTIMES.FUNCIONALIDAD 
VALUES ('ABM_ROL');

insert into GOODTIMES.FUNCIONALIDAD_X_ROL
VALUES (3, SCOPE_IDENTITY());

GO