USE GD1C2014;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_EMPRESA_CIUDAD') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE EMPRESA DROP CONSTRAINT FK_EMPRESA_CIUDAD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_FUNCIONALIDAD_X_ROL_FUNCIONALIDAD') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE FUNCIONALIDAD_X_ROL DROP CONSTRAINT FK_FUNCIONALIDAD_X_ROL_FUNCIONALIDAD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_FUNCIONALIDAD_X_ROL_ROL') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE FUNCIONALIDAD_X_ROL DROP CONSTRAINT FK_FUNCIONALIDAD_X_ROL_ROL;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_USUARIO_CLIENTE') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_CLIENTE;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_USUARIO_EMPRESA') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_EMPRESA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_USUARIO_LOCALIDAD') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE USUARIO DROP CONSTRAINT FK_USUARIO_LOCALIDAD;



IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CIUDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CIUDAD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('CLIENTE') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE CLIENTE;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('EMPRESA') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE EMPRESA;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FUNCIONALIDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE FUNCIONALIDAD;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FUNCIONALIDAD_X_ROL') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE FUNCIONALIDAD_X_ROL;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('ROL') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE ROL;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('USUARIO') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE USUARIO;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('LOCALIDAD') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE LOCALIDAD;


CREATE TABLE CIUDAD ( 
	ID bigint identity(1,1)  NOT NULL,
	NOMBRE nvarchar(max) NOT NULL
);

CREATE TABLE CLIENTE ( 
	ID bigint identity(1,1)  NOT NULL,
	NOMBRE nvarchar(max) NOT NULL,
	APELLIDO nvarchar(max) NOT NULL,
	DNI int NOT NULL,
	DNI_TIPO char(3) NOT NULL,
	FECHA_NAC smalldatetime NOT NULL
);

CREATE TABLE EMPRESA ( 
	CUIT bigint NOT NULL,
	RAZON_SOCIAL nvarchar(max) NOT NULL,
	CONTACTO nvarchar(max) NOT NULL,
	FECHA_CREACION smalldatetime NOT NULL,
	CIUDAD_ID bigint NOT NULL
);

CREATE TABLE FUNCIONALIDAD ( 
	ID int identity(1,1)  NOT NULL,
	NOMBRE nvarchar(max) NOT NULL
);

CREATE TABLE FUNCIONALIDAD_X_ROL ( 
	ROL_ID int NOT NULL,
	FUNCIONALIDAD_ID int NOT NULL
);

CREATE TABLE ROL ( 
	ID int identity(1,1)  NOT NULL,
	NOMBRE nvarchar(50) NOT NULL,
	HABILITADO bit DEFAULT 1 NOT NULL,
	ELIMINADO bit DEFAULT 0 NOT NULL
);

CREATE TABLE USUARIO ( 
	ID bigint identity(1,1)  NOT NULL,
	USERNAME nvarchar(50) NOT NULL,
	PASSWORD nvarchar(max) NOT NULL,
	CLIENTE_ID bigint,
	EMPRESA_ID bigint,
	LOGIN_FALLIDOS int DEFAULT 0 NOT NULL,
	HABILITADO bit DEFAULT 1 NOT NULL,
	ELIMINADO bit DEFAULT 0 NOT NULL,
	MAIL nvarchar(max) NOT NULL,
	TELEFONO int NOT NULL,
	COD_POSTAL int NOT NULL,
	DIRECCION nvarchar(max) NOT NULL,
	PISO smallint NOT NULL,
	DTO char(1) NOT NULL
);

CREATE TABLE LOCALIDAD ( 
	COD_POSTAL int NOT NULL,
	NOMBRE nvarchar(max) NOT NULL
);


ALTER TABLE CIUDAD ADD CONSTRAINT PK_CIUDAD 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA 
	PRIMARY KEY CLUSTERED (CUIT);

ALTER TABLE FUNCIONALIDAD ADD CONSTRAINT PK_FUNCIONALIDAD 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE ROL ADD CONSTRAINT PK_ROL 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO 
	PRIMARY KEY CLUSTERED (ID);

ALTER TABLE LOCALIDAD ADD CONSTRAINT PK_LOCALIDAD 
	PRIMARY KEY CLUSTERED (COD_POSTAL);



ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMPRESA_CIUDAD 
	FOREIGN KEY (CIUDAD_ID) REFERENCES CIUDAD (ID);

ALTER TABLE FUNCIONALIDAD_X_ROL ADD CONSTRAINT FK_FUNCIONALIDAD_X_ROL_FUNCIONALIDAD 
	FOREIGN KEY (FUNCIONALIDAD_ID) REFERENCES FUNCIONALIDAD (ID);

ALTER TABLE FUNCIONALIDAD_X_ROL ADD CONSTRAINT FK_FUNCIONALIDAD_X_ROL_ROL 
	FOREIGN KEY (ROL_ID) REFERENCES ROL (ID);

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_CLIENTE 
	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID);

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_EMPRESA 
	FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (CUIT);

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_LOCALIDAD 
	FOREIGN KEY (COD_POSTAL) REFERENCES LOCALIDAD (COD_POSTAL);
