/*DROP PROCEDURE GOODTIMES.BuscarClientes;
DROP PROCEDURE GOODTIMES.CrearCliente;
DROP PROCEDURE GOODTIMES.CrearEmpresa;*/

CREATE PROCEDURE GOODTIMES.BuscarClientes
@NOMBRE nvarchar(100), 
@APELLIDO nvarchar(100),
@MAIL nvarchar(100), 
@DNI_TIPO nvarchar(10),
@DNI nvarchar(100)
AS
	BEGIN
		SELECT U.ID, U.USERNAME, U.CLIENTE_ID, U.LOGIN_FALLIDOS, U.HABILITADO, U.ELIMINADO, U.MAIL, U.TELEFONO, U.DIRECCION, U.CODIGO_POSTAL, U.LOCALIDAD, C.NOMBRE, C.APELLIDO, C.APELLIDO, C.DNI, C.DNI_TIPO, C.FECHA_NAC 
		FROM GOODTIMES.CLIENTE C, GOODTIMES.USUARIO U
		WHERE U.CLIENTE_ID = C.ID 
		AND C.NOMBRE like ISNULL(@NOMBRE, '%')
		AND C.APELLIDO like ISNULL(@APELLIDO, '%')
		AND U.MAIL like ISNULL(@MAIL, '%')
		AND C.DNI_TIPO like ISNULL(@DNI_TIPO, '%')
		AND C.DNI like ISNULL(@DNI, '%')
	END
GO

CREATE PROCEDURE GOODTIMES.CrearCliente
@NOMBRE nvarchar(100), 
@APELLIDO nvarchar(100), 
@DNI nvarchar(100), 
@DNI_TIPO nvarchar(100), 
@FECHA_NAC nvarchar(100),

@USERNAME nvarchar(100), 
@PASSWORD nvarchar(100),
@LOGIN_FALLIDOS int, 
@HABILITADO bit, 
@ELIMINADO bit, 
@MAIL nvarchar(100), 
@TELEFONO nvarchar(100), 
@DIRECCION nvarchar(100), 
@CODIGO_POSTAL nvarchar(100), 
@LOCALIDAD nvarchar(100)

AS
BEGIN TRANSACTION;

	INSERT INTO GOODTIMES.CLIENTE(NOMBRE, APELLIDO, DNI, DNI_TIPO, FECHA_NAC)
	VALUES (@NOMBRE, @APELLIDO, @DNI, @DNI_TIPO, @FECHA_NAC);
	
	INSERT INTO GOODTIMES.USUARIO(USERNAME, PASSWORD, CLIENTE_ID, LOGIN_FALLIDOS, HABILITADO, ELIMINADO, MAIL, TELEFONO, DIRECCION, CODIGO_POSTAL, LOCALIDAD)
	VALUES (@USERNAME, @PASSWORD, SCOPE_IDENTITY(), @LOGIN_FALLIDOS, @HABILITADO, @ELIMINADO, @MAIL, @TELEFONO, @DIRECCION, @CODIGO_POSTAL, @LOCALIDAD);
	
COMMIT TRANSACTION;

GO

CREATE PROCEDURE GOODTIMES.CrearEmpresa
@RAZON_SOCIAL nvarchar(100), 
@CUIT bigint,
@CONTACTO nvarchar(100), 
@FECHA_CREACION nvarchar(100),

@USERNAME nvarchar(100), 
@PASSWORD nvarchar(100),
@LOGIN_FALLIDOS int, 
@HABILITADO bit, 
@ELIMINADO bit, 
@MAIL nvarchar(100), 
@TELEFONO nvarchar(100), 
@DIRECCION nvarchar(100), 
@CODIGO_POSTAL nvarchar(100), 
@LOCALIDAD nvarchar(100)

AS
BEGIN TRANSACTION;

	INSERT INTO GOODTIMES.EMPRESA(CUIT, RAZON_SOCIAL, CONTACTO, FECHA_CREACION)
	VALUES (@CUIT, @RAZON_SOCIAL, @CONTACTO, @FECHA_CREACION);
	
	INSERT INTO GOODTIMES.USUARIO(USERNAME, PASSWORD, EMPRESA_ID, LOGIN_FALLIDOS, HABILITADO, ELIMINADO, MAIL, TELEFONO, DIRECCION, CODIGO_POSTAL, LOCALIDAD)
	VALUES (@USERNAME, @PASSWORD, @CUIT, @LOGIN_FALLIDOS, @HABILITADO, @ELIMINADO, @MAIL, @TELEFONO, @DIRECCION, @CODIGO_POSTAL, @LOCALIDAD);
	
COMMIT TRANSACTION;

GO