/*

drop procedure GOODTIMES.BuscarClientes;
drop procedure GOODTIMES.CrearCliente;
drop procedure GOODTIMES.CrearEmpresa;
drop procedure GOODTIMES.BuscarEmpresaPorRazonSocial;
drop procedure GOODTIMES.BuscarEmpresaPorCuit;
drop procedure GOODTIMES.BuscarClientePorTelefono;
drop procedure GOODTIMES.BuscarClientePorDNITipoYDNI;
drop procedure GOODTIMES.BuscarUsuarioPorUsername;
drop procedure GOODTIMES.ModificarCliente;
drop procedure GOODTIMES.EliminarUsuario;
drop procedure GOODTIMES.ModificarEmpresa;
drop procedure GOODTIMES.BuscarEmpresas;

*/

CREATE PROCEDURE GOODTIMES.BuscarClientes
@NOMBRE nvarchar(100), 
@APELLIDO nvarchar(100),
@MAIL nvarchar(100), 
@DNI_TIPO nvarchar(10),
@DNI nvarchar(100)
AS
	BEGIN
		SELECT U.ID, U.USERNAME, U.CLIENTE_ID, U.LOGIN_FALLIDOS, U.HABILITADO, U.ELIMINADO, U.MAIL, U.TELEFONO, U.DIRECCION, U.CODIGO_POSTAL, U.LOCALIDAD, C.NOMBRE, C.APELLIDO, C.APELLIDO, C.DNI, C.DNI_TIPO, C.FECHA_NAC 
		FROM GOODTIMES.CLIENTE C, GOODTIMES.USUARIO U
		WHERE U.CLIENTE_ID = C.ID 
		AND C.NOMBRE like ISNULL('%' + @NOMBRE + '%', '%')
		AND C.APELLIDO like ISNULL('%' + @APELLIDO + '%', '%')
		AND U.MAIL like ISNULL('%' + @MAIL + '%', '%')
		AND C.DNI_TIPO like ISNULL('%' + @DNI_TIPO + '%', '%')
		AND C.DNI like ISNULL('%' + @DNI + '%', '%')
		AND U.ELIMINADO = 0;
	END
GO

CREATE PROCEDURE GOODTIMES.CrearCliente
@NOMBRE nvarchar(100), 
@APELLIDO nvarchar(100), 
@DNI nvarchar(100), 
@DNI_TIPO nvarchar(100), 
@FECHA_NAC nvarchar(100),

@USERNAME nvarchar(100), 
@PASSWORD nvarchar(100),
@LOGIN_FALLIDOS int, 
@HABILITADO bit, 
@ELIMINADO bit, 
@MAIL nvarchar(100), 
@TELEFONO nvarchar(100), 
@DIRECCION nvarchar(100), 
@CODIGO_POSTAL nvarchar(100), 
@LOCALIDAD nvarchar(100)

AS
BEGIN TRANSACTION;

	INSERT INTO GOODTIMES.CLIENTE(NOMBRE, APELLIDO, DNI, DNI_TIPO, FECHA_NAC)
	VALUES (@NOMBRE, @APELLIDO, @DNI, @DNI_TIPO, @FECHA_NAC);
	
	INSERT INTO GOODTIMES.USUARIO(USERNAME, PASSWORD, CLIENTE_ID, LOGIN_FALLIDOS, HABILITADO, ELIMINADO, MAIL, TELEFONO, DIRECCION, CODIGO_POSTAL, LOCALIDAD)
	VALUES (@USERNAME, @PASSWORD, SCOPE_IDENTITY(), @LOGIN_FALLIDOS, @HABILITADO, @ELIMINADO, @MAIL, @TELEFONO, @DIRECCION, @CODIGO_POSTAL, @LOCALIDAD);
	
COMMIT TRANSACTION;

GO

CREATE PROCEDURE GOODTIMES.CrearEmpresa
@RAZON_SOCIAL nvarchar(100), 
@CUIT bigint,
@CONTACTO nvarchar(100), 
@FECHA_CREACION nvarchar(100),

@USERNAME nvarchar(100), 
@PASSWORD nvarchar(100),
@LOGIN_FALLIDOS int, 
@HABILITADO bit, 
@ELIMINADO bit, 
@MAIL nvarchar(100), 
@TELEFONO nvarchar(100), 
@DIRECCION nvarchar(100), 
@CODIGO_POSTAL nvarchar(100), 
@LOCALIDAD nvarchar(100)

AS
BEGIN TRANSACTION;

	INSERT INTO GOODTIMES.EMPRESA(CUIT, RAZON_SOCIAL, CONTACTO, FECHA_CREACION)
	VALUES (@CUIT, @RAZON_SOCIAL, @CONTACTO, @FECHA_CREACION);
	
	INSERT INTO GOODTIMES.USUARIO(USERNAME, PASSWORD, EMPRESA_ID, LOGIN_FALLIDOS, HABILITADO, ELIMINADO, MAIL, TELEFONO, DIRECCION, CODIGO_POSTAL, LOCALIDAD)
	VALUES (@USERNAME, @PASSWORD, SCOPE_IDENTITY(), @LOGIN_FALLIDOS, @HABILITADO, @ELIMINADO, @MAIL, @TELEFONO, @DIRECCION, @CODIGO_POSTAL, @LOCALIDAD);
	
COMMIT TRANSACTION;

GO



CREATE PROCEDURE GOODTIMES.BuscarEmpresaPorRazonSocial
@RAZON_SOCIAL nvarchar(100)

AS
	SELECT E.CUIT, E.RAZON_SOCIAL, E.CONTACTO, E.FECHA_CREACION, U.ID, U.USERNAME, U.CLIENTE_ID, U.LOGIN_FALLIDOS, U.HABILITADO, U.ELIMINADO, U.MAIL, U.TELEFONO, U.DIRECCION, U.CODIGO_POSTAL, U.LOCALIDAD 
	FROM GOODTIMES.USUARIO U, GOODTIMES.EMPRESA E 
	WHERE U.EMPRESA_ID = E.ID AND
	E.RAZON_SOCIAL = @RAZON_SOCIAL;
GO

CREATE PROCEDURE GOODTIMES.BuscarEmpresaPorCuit
@CUIT bigint

AS
	SELECT E.CUIT, E.RAZON_SOCIAL, E.CONTACTO, E.FECHA_CREACION, U.ID, U.USERNAME, U.CLIENTE_ID, U.LOGIN_FALLIDOS, U.HABILITADO, U.ELIMINADO, U.MAIL, U.TELEFONO, U.DIRECCION, U.CODIGO_POSTAL, U.LOCALIDAD
	FROM GOODTIMES.USUARIO U, GOODTIMES.EMPRESA E 
	WHERE U.EMPRESA_ID = E.ID AND
	E.CUIT = @CUIT;
GO

CREATE PROCEDURE GOODTIMES.BuscarClientePorTelefono
@TELEFONO nvarchar(100)

AS
	SELECT U.ID, U.USERNAME, U.CLIENTE_ID, U.LOGIN_FALLIDOS, U.HABILITADO, U.ELIMINADO, U.MAIL, U.TELEFONO, U.DIRECCION, U.CODIGO_POSTAL, U.LOCALIDAD, C.NOMBRE, C.APELLIDO, C.APELLIDO, C.DNI, C.DNI_TIPO, C.FECHA_NAC 
	FROM GOODTIMES.CLIENTE C, GOODTIMES.USUARIO U 
	WHERE U.CLIENTE_ID = C.ID AND
	      U.TELEFONO = @TELEFONO;
GO

CREATE PROCEDURE GOODTIMES.BuscarClientePorDNITipoYDNI
@DNI_TIPO nvarchar(10),
@DNI nvarchar(100)

AS
	SELECT U.ID, U.USERNAME, U.CLIENTE_ID, U.LOGIN_FALLIDOS, U.HABILITADO, U.ELIMINADO, U.MAIL, U.TELEFONO, U.DIRECCION, U.CODIGO_POSTAL, U.LOCALIDAD, C.NOMBRE, C.APELLIDO, C.APELLIDO, C.DNI, C.DNI_TIPO, C.FECHA_NAC 
	FROM GOODTIMES.CLIENTE C, GOODTIMES.USUARIO U 
	WHERE U.CLIENTE_ID = C.ID AND
	C.DNI_TIPO = @DNI_TIPO AND
	c.DNI = @DNI;
GO

CREATE PROCEDURE GOODTIMES.BuscarUsuarioPorUsername
@USERNAME nvarchar(100)

AS
	SELECT * FROM GOODTIMES.USUARIO 
	WHERE USERNAME = @USERNAME;
GO


CREATE PROCEDURE GOODTIMES.ModificarCliente
@NOMBRE nvarchar(100), 
@APELLIDO nvarchar(100), 
@DNI nvarchar(100), 
@DNI_TIPO nvarchar(100), 
@FECHA_NAC nvarchar(100),
@CLIENTE_ID bigint,

@ID bigint,
@USERNAME nvarchar(100),
@HABILITADO bit, 
@ELIMINADO bit, 
@MAIL nvarchar(100), 
@TELEFONO nvarchar(100), 
@DIRECCION nvarchar(100), 
@CODIGO_POSTAL nvarchar(100), 
@LOCALIDAD nvarchar(100),
@LOGIN_FALLIDOS int

AS
BEGIN TRANSACTION;

	UPDATE GOODTIMES.CLIENTE
	SET NOMBRE = @NOMBRE,
	APELLIDO = @APELLIDO, 
	DNI = @DNI, 
	DNI_TIPO = @DNI_TIPO, 
	FECHA_NAC = @FECHA_NAC
	WHERE ID = @CLIENTE_ID;
	
	UPDATE GOODTIMES.USUARIO
	SET USERNAME = @USERNAME,
	HABILITADO = @HABILITADO,
	ELIMINADO = @ELIMINADO,
	MAIL = @MAIL,
	TELEFONO = @TELEFONO,
	DIRECCION = @DIRECCION,
	CODIGO_POSTAL = @CODIGO_POSTAL,
	LOCALIDAD = @LOCALIDAD,
	LOGIN_FALLIDOS = @LOGIN_FALLIDOS
	WHERE ID = @ID;
	
COMMIT TRANSACTION;

GO 

CREATE PROCEDURE GOODTIMES.EliminarUsuario
@ID bigint

AS
	UPDATE GOODTIMES.USUARIO
	SET ELIMINADO = 1
	WHERE ID = @ID;
GO


CREATE PROCEDURE GOODTIMES.ModificarEmpresa

@RAZON_SOCIAL nvarchar(100), 
@CUIT bigint,
@CONTACTO nvarchar(100), 
@FECHA_CREACION nvarchar(100),
@EMPRESA_ID bigint,

@ID bigint,
@USERNAME nvarchar(100),
@LOGIN_FALLIDOS int, 
@HABILITADO bit, 
@ELIMINADO bit, 
@MAIL nvarchar(100), 
@TELEFONO nvarchar(100), 
@DIRECCION nvarchar(100), 
@CODIGO_POSTAL nvarchar(100), 
@LOCALIDAD nvarchar(100)

AS
BEGIN TRANSACTION

	UPDATE GOODTIMES.EMPRESA
	SET RAZON_SOCIAL = @RAZON_SOCIAL,
	CONTACTO = @CONTACTO, 
	FECHA_CREACION = @FECHA_CREACION,
	CUIT = @CUIT
	WHERE ID = @EMPRESA_ID;


	UPDATE GOODTIMES.USUARIO
	SET USERNAME = @USERNAME,
	HABILITADO = @HABILITADO,
	ELIMINADO = @ELIMINADO,
	MAIL = @MAIL,
	TELEFONO = @TELEFONO,
	DIRECCION = @DIRECCION,
	CODIGO_POSTAL = @CODIGO_POSTAL,
	LOCALIDAD = @LOCALIDAD,
	LOGIN_FALLIDOS = @LOGIN_FALLIDOS,
	EMPRESA_ID = @EMPRESA_ID
	WHERE ID = @ID;
	
COMMIT TRANSACTION;

GO 

CREATE PROCEDURE GOODTIMES.BuscarEmpresas
@RAZON_SOCIAL nvarchar(100), 
@CUIT nvarchar(100),
@CONTACTO nvarchar(100)
AS
	BEGIN
		SELECT E.CUIT, E.RAZON_SOCIAL, E.CONTACTO, E.FECHA_CREACION, U.ID, U.USERNAME, U.EMPRESA_ID, U.LOGIN_FALLIDOS, U.HABILITADO, U.ELIMINADO, U.MAIL, U.TELEFONO, U.DIRECCION, U.CODIGO_POSTAL, U.LOCALIDAD 
		FROM GOODTIMES.USUARIO U, GOODTIMES.EMPRESA E 
		WHERE U.EMPRESA_ID = E.ID
		AND E.RAZON_SOCIAL like ISNULL('%' + @RAZON_SOCIAL + '%', '%')
		AND E.CUIT like ISNULL('%' + @CUIT + '%', '%')
		AND E.CONTACTO like ISNULL('%' + @CONTACTO + '%', '%')
		AND U.ELIMINADO = 0;
	END
GO